### ISSUE TITLE
Pull request for minor fixes

### ISSUE THREAD

**Issue by michel-slm** [fab13n/metalua#1]
I just committed three sets of changes to my copy of metalua; the last two (LICENSE UTF-8 conversion and DESTDIR support) are definitely safe; the first one (documentation pruning) might be a bit iffy. Would it be possible to get them committed (and metalua 0.5 released soon)?

I'm getting metalua packaged for Fedora Linux, and the DESTDIR change is particularly needed (the LICENSE fix would save us having to use iconv at build time to fix the encoding as well).

**Comment by fab13n** [comment]
Thanks, and sorry for the extremely long delay :) Your fixes have been added in my master branch.
