### ISSUE TITLE
Unable to compile Lua source file

### ISSUE THREAD

**Issue by KINFOO** [fab13n/metalua#11]
Hi,
I'm working on _luaeclipse_ branch.
When trying to compile a plain lua file I get:

```
M> =mlc.luafile_to_ast("/d/runs/spaces/spaces/src/errornode.lua")
Evaluation error:
Parsing error in @/d/runs/spaces/spaces/src/errornode.lua line 10, column 29, char 316: 
interrupted!
stack traceback:
    [C]: in function 'error'
    compiler/mlc.mlua:142: in function <compiler/mlc.mlua:103>
    (tail call): ?
    (tail call): ?
    [C]: in function 'xpcall'
    /d/metalua/build/lib/metalua/metaloop.mlua:56: in function 'run'
    compiler/metalua.mlua:251: in function 'main'
    compiler/metalua.mlua:258: in main chunk
    (tail call): ?
    [C]: ?
```

Here is the file

```
local Q = require 'metalua.treequery'
local sources = {
    notypo   = "function() end",
    onetypo  = "function() typo end",
    twotypos = "function() typo retypo end"
}
for sample, source in pairs(sources) do
    local generated, ast = pcall(mlc.luastring_to_ast, source)
    if generated then x
        local status, message = pcall(mlc.check_ast, ast)
        if not status then
            print ('On sample: '..sample)
            print (message)
        else
            local errornode = Q(ast):filter('Error'):first()
            if not errornode then
                print 'No error node in ast'
            else
                print 'Error node found'
                table.print(errornode, 'nohash', 1)
            end
        end
    else
        print('No AST generated for '..sample)
    end
end
```

Am I doing something wrong or did I find a bug?

**Comment by fab13n** [comment]
Your file is faulty at line 10, look at the extra "x". That's an incorrect
handling of invalid files, though; I'll check that when I'm back, on
thursday.

On Tue, Dec 27, 2011 at 7:39 PM, Kevin KIN-FOO <
reply@reply.github.com

> wrote:
> 
> Hi,
> I'm working on _luaeclipse_ branch.
> When trying to compile a plain lua file I get:
> 
> ```
>    M> =mlc.luafile_to_ast("/d/runs/spaces/spaces/src/errornode.lua")
>    Evaluation error:
>    Parsing error in @/d/runs/spaces/spaces/src/errornode.lua line 10,
> ```
> 
> column 29, char 316:
>        interrupted!
>        stack traceback:
>                [C]: in function 'error'
>                compiler/mlc.mlua:142: in function <compiler/mlc.mlua:103>
>                (tail call): ?
>                (tail call): ?
>                [C]: in function 'xpcall'
>                /d/metalua/build/lib/metalua/metaloop.mlua:56: in function
> 'run'
>                compiler/metalua.mlua:251: in function 'main'
>                compiler/metalua.mlua:258: in main chunk
>                (tail call): ?
>                [C]: ?
> Here is the file
> 
> ```
>    local Q = require 'metalua.treequery'
>    local sources = {
>            notypo   = "function() end",
>            onetypo  = "function() typo end",
>            twotypos = "function() typo retypo end"
>    }
>    for sample, source in pairs(sources) do
>            local generated, ast = pcall(mlc.luastring_to_ast, source)
>            if generated then x
>                    local status, message = pcall(mlc.check_ast, ast)
>                    if not status then
>                            print ('On sample: '..sample)
>                            print (message)
>                    else
>                            local errornode =
> ```
> 
> Q(ast):filter('Error'):first()
>                                if not errornode then
>                                        print 'No error node in ast'
>                                else
>                                        print 'Error node found'
>                                        table.print(errornode, 'nohash', 1)
>                                end
>                        end
>                else
>                        print('No AST generated for '..sample)
>                end
>        end
> Am I doing something wrong or did I find a bug?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fab13n/metalua/issues/11

## 

Fabien Fleutot
+---
| 33 chemin de Mange-Pommes
| 31520 Ramonville Saint-Agne -- France
| mobile: +33 6 28 06 09 97
| office: +33 5 61 00 06 49
| home: +33 5 61 75 05 67

**Comment by KINFOO** [comment]
My bad,
Without the typo, I get:

```
% ./metalua /d/runs/spaces/spaces/src/errornode.lua
No AST generated for twotypos
On sample: onetypo
compiler/mlc.mlua:44: wrong AST type

compiler/mlc.mlua:44: wrong AST type
```

For code:

```
local Q = require 'metalua.treequery'
local sources = {
    onetypo  = "function() typo end",
    twotypos = "function() typo retypo end"
}
for sample, source in pairs(sources) do
    local generated, ast = pcall(mlc.luastring_to_ast, source)
    if generated then
        local status, message = pcall(mlc.check_ast, ast)
        if not status then
            print ('On sample: '..sample)
            print (message)
        else
            local errornode = Q(ast):filter('Error'):first()
            if not errornode then
                print 'No error node in ast'
            else
                print 'Error node found'
                table.print(errornode, 'nohash', 1)
            end
        end
    else
        print('No AST generated for '..sample)
    end
end
```

So I think error nodes are not generated in both cases.
We'll sort this out Thursday.
Cheers

**Comment by fab13n** [comment]
Well, fixing this unraveled an embarrassing series of bugs introduced in the errornodes branch. The newest luaeclipse commit should fix these. Also, let me suggest an alternative "fail loudly" version of your test:

```
local Q = require 'metalua.treequery'
local sources = {
    onetypo  = "one();function() typo end",
    twotypos = "two();function() typo retypo end"
}

for sample, source in pairs(sources) do
    printf(" *** Sample %s ***", sample)
    local ast = mlc.luastring_to_ast(source)
    local status, message = pcall(mlc.check_ast, ast)
    if not status then
        print ('On sample: '..sample)
        print (message)
    else
        local errornode = Q(ast):filter('Error'):first()
        if not errornode then
            print 'No error node in ast'
        else
            print 'Error node found'
            table.print(errornode, 'nohash', 1)
        end
    end
end
```
