### ISSUE TITLE
unbound variables is not caught by bindings

### ISSUE THREAD

**Issue by sbernard31** [fab13n/metalua#13]
with this code : 

```
local toto
for var =1, 0 do
    var = 2
end 

for _ in toto() do
    var()
    var = var() 
end
```

bindings returns an empty list for the unbound variables

**Comment by KINFOO** [comment]
Hi,
I think I might have the same kind of problem, with this code

```
d = nil
function f()
    local d
end
```

`d` is in the list of unbound variables. But not in the following one:

```
function f()
    local d
end
d = nil
```

This may be a bug, because the scopes are the same, even at runtime.

**Comment by fab13n** [comment]
bug only existed in branch luaeclipse, now fixed.

**Comment by KINFOO** [comment]
Now backported to _konekildt_.

**Comment by KINFOO** [comment]
It seem that this case still has a strange behavior.

```
local toto
for var =1, 0 do
    var = 2
end 

for _ in toto() do
    var()
    var = var() 
end
```

`bindings` does not provides occurences for the second block
