### ISSUE TITLE
Cannot print ast with metalua.lua

### ISSUE THREAD

**Issue by wanghc78** [fab13n/metalua#23]
Run with lua ./metalua.lua --file helloworld.lua --print-ast
And it throws exceptions.
1. From the block of metalua.lua:177 
   it sets the new tag Return node, but there is no source field for the node. So it causes line 195 exception.
2. the line 200. The pp.print has 3 arguments, but the metalua/pprint.lua's function accepts only 2.
3. It seems the table's extension is not enabled in this version. And line 209 table.tostring causes problem.

I believe there some bugs introduced by inconsistent versions of code.

**Comment by fab13n** [comment]
Does commit 1fec8ed671542b24af7d36c890757b85797ed250 fix your issue?

**Comment by wanghc78** [comment]
Fixed. Thank you!
