### ISSUE TITLE
Bug using binding function

### ISSUE THREAD

**Issue by KINFOO** [fab13n/metalua#3]
When searching for variable declarations with bindings, I get an loop error when ther are "..." in the parsed source
    require 'bind'
    require 'metalua.walk.bindings'
    local declared, leftovers = bindings( mlc.luastring_to_ast("sample = function( ... ) end") ) 
    .../Bureau/metalua/build/lib/metalua/walk/bindings.mlua:17: table index is nil
    stack traceback:
        .../Bureau/metalua/build/lib/metalua/walk/bindings.mlua:17: in function 'f'
        ...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:292: in function <...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:290>
        (tail call): ?
        ...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:226: in function 'traverse'
        ...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:275: in function 'expr'
        ...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:249: in function 'traverse'
        ...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:275: in function <...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:259>
        (tail call): ?
        ...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:193: in function 'traverse'
        ...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:275: in function 'stat'
        ...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:243: in function 'traverse'
        ...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:275: in function <...e/kkinfoo/Bureau/metalua/build/lib/metalua/walk.mlua:259>
        (tail call): ?
        .../Bureau/metalua/build/lib/metalua/walk/bindings.mlua:39: in function 'bindings'
        stdin:1: in main chunk
        [C]: ?

**Comment by fab13n** [comment]
fixed in the head, cf. src/lib/metalua/walk.mlua l.292
