### ISSUE TITLE
Bug: Unknown escape sequence '\.'

### ISSUE THREAD

**Issue by KINFOO** [fab13n/metalua#4]
Hi,

I'm on branch _origin/luaeclipse_, using my installed Metalua, I parse a lua file that Metalua seems to not understand.

``` shell
$ lua win32.lua
$ metalua win32.lua 
lua: compiler/mlc.mlua:106: Parsing error in @win32.lua line 18, column 17, char 593: 
lexer.lua:91: Unknown escape sequence '\.'
 - (l.18, c.17, k.593) in parser ( ... )
 - (l.18, c.17, k.593) in parser function argument(s)
 - (l.18, c.8, k.584) in parser expression
 - (l.18, c.8, k.584) in parser <anonymous>
 - (l.18, c.8, k.584) in parser list
 - (l.18, c.5, k.581) in parser if ... end
 - (l.18, c.5, k.581) in parser statement
 - (l.16, c.4, k.519) in parser statements block
 - (l.15, c.11, k.510) in parser <anonymous>
 - (l.15, c.1, k.500) in parser function ...
 - (l.15, c.1, k.500) in parser statement
 - (l.15, c.1, k.500) in parser statements block
 - (l.15, c.1, k.500) in parser <anonymous>
stack traceback:
    [C]: in function 'error'
    compiler/mlc.mlua:106: in function <compiler/mlc.mlua:69>
    (tail call): ?
    ...ome/kkinfoo/.bin/local/lib/lua/metalua/mlc_xcall.lua:13: in function 'server'
    (command line):1: in main chunk
    [C]: ?
/usr/bin/lua: ...ome/kkinfoo/.bin/local/lib/lua/metalua/mlc_xcall.lua:31: xcall failure. FIXME: transmit failure and backtrace
stack traceback:
    [C]: in function 'error'
    ...ome/kkinfoo/.bin/local/lib/lua/metalua/mlc_xcall.lua:31: in function 'client_file'
    compiler/metalua.mlua:142: in function 'main'
    compiler/metalua.mlua:256: in main chunk
    (tail call): ?
    [C]: ?

```

Here is the file that generates the error:

``` lua
--- Windows implementation of filesystem and platform abstractions.
-- Download http://unxutils.sourceforge.net/ for Windows GNU utilities
-- used by this module.
--[[module("luarocks.fs.win32", package.seeall)

local fs = require("luarocks.fs")

local cfg = require("luarocks.cfg")
local dir = require("luarocks.dir")
]]
--- Quote argument for shell processing. Fixes paths on Windows.
-- Adds single quotes and escapes.
-- @param arg string: Unquoted argument.
-- @return string: Quoted argument.
function Q(arg)
   assert(type(arg) == "string")
   -- Quote DIR for Windows
    if arg:match("^[\.a-zA-Z]?:?[\\/]")  then
        return '"' .. arg:gsub("/", "\\"):gsub('"', '\\"') .. '"'
    end
    -- URLs and anything else
   return '"' .. arg:gsub('"', '\\"') .. '"'
end

--- Return an absolute pathname from a potentially relative one.
-- @param pathname string: pathname to convert.
-- @param relative_to string or nil: path to prepend when making
-- pathname absolute, or the current dir in the dir stack if
-- not given.
-- @return string: The pathname converted to absolute.
function absolute_name(pathname, relative_to)
   assert(type(pathname) == "string")
   assert(type(relative_to) == "string" or not relative_to)

   relative_to = relative_to or fs.current_dir()
   if pathname:match("^[\.a-zA-Z]?:?[\\/]") then
      return pathname
   else
      return relative_to .. "/" .. pathname
   end
end

--- Create a wrapper to make a script executable from the command-line.
-- @param file string: Pathname of script to be made executable.
-- @param dest string: Directory where to put the wrapper.
-- @return boolean or (nil, string): True if succeeded, or nil and
-- an error message.
function wrap_script(file, dest)
   assert(type(file) == "string")
   assert(type(dest) == "string")

   local base = dir.base_name(file)
   local wrapname = fs.is_dir(dest) and dest.."/"..base or dest
   wrapname = wrapname..".bat"
   local wrapper = io.open(wrapname, "w")
   if not wrapper then
      return nil, "Could not open "..wrapname.." for writing."
   end
   wrapper:write("@echo off\n")
   wrapper:write("setlocal\n")
   wrapper:write('set LUA_PATH='..package.path..";%LUA_PATH%\n")
   wrapper:write('set LUA_CPATH='..package.cpath..";%LUA_CPATH%\n")
   wrapper:write('"'..dir.path(cfg.variables["LUA_BINDIR"], cfg.lua_interpreter)..'" -lluarocks.loader "'..file..'" %*\n')
   wrapper:write("endlocal\n")
   wrapper:close()
   return true
end

function is_actual_binary(name)
   name = name:lower()
   if name:match("%.bat$") or name:match("%.exe$") then
      return true
   end
   return false
end

function copy_binary(filename, dest) 
   local ok, err = fs.copy(filename, dest)
   if not ok then
      return nil, err
   end
   local exe_pattern = "%.[Ee][Xx][Ee]$"
   local base = dir.base_name(filename)
   local dest = dir.dir_name(dest)
   if base:match(exe_pattern) then
      base = base:gsub(exe_pattern, ".lua")
      local helpname = dest.."/"..base
      local helper = io.open(helpname, "w")
      if not helper then
         return nil, "Could not open "..helpname.." for writing."
      end
      helper:write('package.path=\"'..package.path:gsub("\\","\\\\")..';\"..package.path\n')
      helper:write('package.cpath=\"'..package.path:gsub("\\","\\\\")..';\"..package.cpath\n')
      helper:close()
   end
   return true
end

function chmod(filename, mode)
   return true
end

function get_permissions(filename)
   return ""
end
```

**Comment by fab13n** [comment]
A mon avis, cette sequence est illegale, et c'est le compilo Lua qui a tort
de l'accepter.
Eventuellement, je peux reverse engineerer le compilo de reference pour voir
ce qu'il accepte comme sequences, et rendre metalua plus permissif. En
attendant, je suggere d'utiliser des fichiers syntaxiquement corrects :)

On Thu, May 19, 2011 at 11:55 AM, KINFOO <
reply@reply.github.com>wrote:

> Hi,
> 
> I'm on branch _origin/luaeclipse_, using my installed Metalua, I parse a
> lua file that Metalua seems to not understand.
> 
> ``` shell
> $ lua win32.lua
> $ metalua win32.lua
> lua: compiler/mlc.mlua:106: Parsing error in @win32.lua line 18, column 17,
> char 593:
> lexer.lua:91: Unknown escape sequence '\.'
>  - (l.18, c.17, k.593) in parser ( ... )
>  - (l.18, c.17, k.593) in parser function argument(s)
>  - (l.18, c.8, k.584) in parser expression
>  - (l.18, c.8, k.584) in parser <anonymous>
>  - (l.18, c.8, k.584) in parser list
>  - (l.18, c.5, k.581) in parser if ... end
>  - (l.18, c.5, k.581) in parser statement
>  - (l.16, c.4, k.519) in parser statements block
>  - (l.15, c.11, k.510) in parser <anonymous>
>  - (l.15, c.1, k.500) in parser function ...
>  - (l.15, c.1, k.500) in parser statement
>  - (l.15, c.1, k.500) in parser statements block
>  - (l.15, c.1, k.500) in parser <anonymous>
> stack traceback:
>        [C]: in function 'error'
>        compiler/mlc.mlua:106: in function <compiler/mlc.mlua:69>
>        (tail call): ?
>        ...ome/kkinfoo/.bin/local/lib/lua/metalua/mlc_xcall.lua:13: in
> function 'server'
>        (command line):1: in main chunk
>        [C]: ?
> /usr/bin/lua: ...ome/kkinfoo/.bin/local/lib/lua/metalua/mlc_xcall.lua:31:
> xcall failure. FIXME: transmit failure and backtrace
> stack traceback:
>        [C]: in function 'error'
>        ...ome/kkinfoo/.bin/local/lib/lua/metalua/mlc_xcall.lua:31: in
> function 'client_file'
>        compiler/metalua.mlua:142: in function 'main'
>        compiler/metalua.mlua:256: in main chunk
>        (tail call): ?
>        [C]: ?
> 
> ```
> 
> Here is the file that generates the error:
> 
> ``` lua
> --- Windows implementation of filesystem and platform abstractions.
> -- Download http://unxutils.sourceforge.net/ for Windows GNU utilities
> -- used by this module.
> --[[module("luarocks.fs.win32", package.seeall)
> 
> local fs = require("luarocks.fs")
> 
> local cfg = require("luarocks.cfg")
> local dir = require("luarocks.dir")
> ]]
> --- Quote argument for shell processing. Fixes paths on Windows.
> -- Adds single quotes and escapes.
> -- @param arg string: Unquoted argument.
> -- @return string: Quoted argument.
> function Q(arg)
>   assert(type(arg) == "string")
>   -- Quote DIR for Windows
>    if arg:match("^[\.a-zA-Z]?:?[\\/]")  then
>        return '"' .. arg:gsub("/", "\\"):gsub('"', '\\"') .. '"'
>    end
>    -- URLs and anything else
>   return '"' .. arg:gsub('"', '\\"') .. '"'
> end
> 
> --- Return an absolute pathname from a potentially relative one.
> -- @param pathname string: pathname to convert.
> -- @param relative_to string or nil: path to prepend when making
> -- pathname absolute, or the current dir in the dir stack if
> -- not given.
> -- @return string: The pathname converted to absolute.
> function absolute_name(pathname, relative_to)
>   assert(type(pathname) == "string")
>   assert(type(relative_to) == "string" or not relative_to)
> 
>   relative_to = relative_to or fs.current_dir()
>   if pathname:match("^[\.a-zA-Z]?:?[\\/]") then
>      return pathname
>   else
>      return relative_to .. "/" .. pathname
>   end
> end
> 
> --- Create a wrapper to make a script executable from the command-line.
> -- @param file string: Pathname of script to be made executable.
> -- @param dest string: Directory where to put the wrapper.
> -- @return boolean or (nil, string): True if succeeded, or nil and
> -- an error message.
> function wrap_script(file, dest)
>   assert(type(file) == "string")
>   assert(type(dest) == "string")
> 
>   local base = dir.base_name(file)
>   local wrapname = fs.is_dir(dest) and dest.."/"..base or dest
>   wrapname = wrapname..".bat"
>   local wrapper = io.open(wrapname, "w")
>   if not wrapper then
>      return nil, "Could not open "..wrapname.." for writing."
>   end
>   wrapper:write("@echo off\n")
>   wrapper:write("setlocal\n")
>   wrapper:write('set LUA_PATH='..package.path..";%LUA_PATH%\n")
>   wrapper:write('set LUA_CPATH='..package.cpath..";%LUA_CPATH%\n")
>   wrapper:write('"'..dir.path(cfg.variables["LUA_BINDIR"],
> cfg.lua_interpreter)..'" -lluarocks.loader "'..file..'" %*\n')
>   wrapper:write("endlocal\n")
>   wrapper:close()
>   return true
> end
> 
> function is_actual_binary(name)
>   name = name:lower()
>   if name:match("%.bat$") or name:match("%.exe$") then
>      return true
>   end
>   return false
> end
> 
> function copy_binary(filename, dest)
>   local ok, err = fs.copy(filename, dest)
>   if not ok then
>      return nil, err
>   end
>   local exe_pattern = "%.[Ee][Xx][Ee]$"
>   local base = dir.base_name(filename)
>   local dest = dir.dir_name(dest)
>   if base:match(exe_pattern) then
>      base = base:gsub(exe_pattern, ".lua")
>      local helpname = dest.."/"..base
>      local helper = io.open(helpname, "w")
>      if not helper then
>         return nil, "Could not open "..helpname.." for writing."
>      end
> 
>  helper:write('package.path=\"'..package.path:gsub("\\","\\\\")..';\"..package.path\n')
> 
>  helper:write('package.cpath=\"'..package.path:gsub("\\","\\\\")..';\"..package.cpath\n')
>      helper:close()
>   end
>   return true
> end
> 
> function chmod(filename, mode)
>   return true
> end
> 
> function get_permissions(filename)
>   return ""
> end
> ```
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fab13n/metalua/issues/4

## 

Fabien Fleutot
+---
| 33 chemin de Mange-Pommes
| 31520 Ramonville Saint-Agne -- France
| mobile: +33 6 28 06 09 97
| office: +33 5 61 00 06 49
| home: +33 5 61 75 05 67
