### ISSUE TITLE
Unable to walk through `Pair

### ISSUE THREAD

**Issue by KINFOO** [fab13n/metalua#5]
Hi,
I use Metalua to explore a Lua AST and I would like to traverse every node.
Unfortunately I do not manage to traverse `Pairs nodes.
I've written the following code to explain.

```
local traverse = function(node, ...)
    -- Just print node's type
    if node and node.tag then print(node.tag) end
end
local cfg = {
    binder = traverse,
    block = { up = traverse },
    expr  = { up = traverse },
    stat  = { up = traverse },
    Pair  = traverse
}
require 'metalua.compiler'
local ast = mlc.luastring_to_ast("table={p=1}")
require 'metalua.walk'
walk.block(cfg, ast)
```

Here is my output

```
Id
String
Number
Table
Set
```

I'm on branch LuaEclipse
Is it a bug? Am I doing it the wrong way?
Regards

**Comment by fab13n** [comment]
It's not a bug, it's a feature :)
- Pairs aren't expr (although their 2 halves are), so they shouldn't trigger
  cfg.expr
- Pairs aren't stat, so they shouldn't trigger cfg.stat
- Pairs aren't block, so they shouldn't trigger cfg.block

It's the same as intermediate left-hand and right-hand lists in `Local and
`Set nodes: these lists/structures aren't valid bits of Lua AST taken out of
context, and shouldn't be traversed explicitly. If you want to do something
with them, catch them when going down `Table nodes: those are valid (expr)
nodes.

On Mon, Aug 8, 2011 at 4:28 PM, KINFOO <
reply@reply.github.com>wrote:

> Hi,
> I use Metalua to explore a Lua AST and I would like to traverse every node.
> Unfortunately I do not manage to traverse `Pairs nodes.
> I've written the following code to explain.
> 
> ```
>    local traverse = function(node, ...)
>            -- Just print node's type
>            if node and node.tag then print(node.tag) end
>    end
>    local cfg = {
>            binder = traverse,
>            block = { up = traverse },
>            expr  = { up = traverse },
>            stat  = { up = traverse },
>            Pair  = traverse
>    }
>    require 'metalua.compiler'
>    local ast = mlc.luastring_to_ast("table={p=1}")
>    require 'metalua.walk'
>    walk.block(cfg, ast)
> ```
> 
> Here is my output
> 
> ```
>    Id
>    String
>    Number
>    Table
>    Set
> ```
> 
> I'm on branch LuaEclipse
> Is it a bug? Am I doing it the wrong way?
> Regards
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fab13n/metalua/issues/5

## 

Fabien Fleutot
+---
| 33 chemin de Mange-Pommes
| 31520 Ramonville Saint-Agne -- France
| mobile: +33 6 28 06 09 97
| office: +33 5 61 00 06 49
| home: +33 5 61 75 05 67
