### ISSUE TITLE
I fix some bugs in table2, how I can pushing it?

### ISSUE THREAD

**Issue by Mingun** [fab13n/metalua#7]
I fixed some very small bugs for the sake of which I do not want to do fork. Please, accept them.
Sorry my bad english.

There is fixed version:

<pre><code class="lua">
-- iforeach(f[[, first], last], t1[, t2[,...]])
function table.iforeach(f, ...)
   -- assert (type (f) == "function") [wouldn't allow metamethod __call]
   local nargs = select("#", ...)
   if nargs==1 then -- Quick iforeach (most common case), just one table arg
      local t = ...
      assert (type (t) == "table")
      for i = 1, #t do 
         local result = f (t[i])
         -- If the function returns non-false, stop iteration
         if result then return result end
      end
   else -- advanced case: boundaries and/or multiple tables
      -- 1 - find boundaries if any
      local  args, fargs, first, last, arg1 = {...}, { }
      if     type(args[1]) ~= "number" then first, arg1 = 1, 1
      elseif type(args[2]) ~= "number" then first, last, arg1 = 1, args[1], 2
      else   first, last, arg1 = args[1], args[2], 3 end
      assert (nargs >= arg1)
      -- 2 - determine upper boundary if not given
      if not last then for i = arg1, nargs do 
         assert (type (args[i]) == "table")
         last = max (#args[i], last) 
      end end
      -- 3 - perform the iteration
      for i = first, last do
         for j = arg1, nargs do fargs[j-arg1+1] = args[j][i] end -- build args list
         local result = f (unpack (fargs)) -- here is the call
         -- If the function returns non-false, stop iteration
         if result then return result end
      end
   end
end
</code></pre>

**Comment by KINFOO** [comment]
Hi,
You can fill a pull request at https://github.com/fab13n/metalua/pulls
Regards
Le 10 sept. 2011 14:21, "Mingun" <
reply@reply.github.com> a
crit :

**Comment by Mingun** [comment]
Hm... when I press 'o' or Enter to make pull request, happens nothing or there is an error 404. You how all the same it to make couldn't explain. Perhaps I at first should make fork?
Sorry my bad english.
